/* tslint:disable */
/* eslint-disable */
/* prettier-ignore */

/* auto-generated by NAPI-RS */

const { existsSync } = require('fs')
const { join } = require('path')
const { parseTriple } = require('./src/utils')
const { Qjsc } = require('./src/qjsc')

let nativeBinding = null
let localFileExisted = false
let loadError = null

const targetTriple = parseTriple()

localFileExisted = existsSync(join(__dirname, `qjsc.${targetTriple}.node`))

try {
  if (localFileExisted) {
    nativeBinding = require(`./qjsc.${targetTriple}.node`)
  } else {
    nativeBinding = require(`@ftajs/qjsc-${targetTriple}`)
  }
} catch (e) {
  loadError = e
}

if (!nativeBinding) {
  if (loadError) {
    throw loadError
  }
  throw new Error(`Failed to load native binding`)
}

module.exports.qjsc = new Qjsc({ bindings: nativeBinding })
