/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

declare class Qjsc {
  constructor(options?: {})
  help(): void
  getSupportedVersions(): string[]
  compile(code: string, options?: {}): any
  get version(): string
  _evalByteCode(buffer: any): any
}

export declare const qjsc: Qjsc
export declare const qjsc3: Qjsc
